const lessonTitle = "迟到";

const lessonData = [
    // 正文第 1 段
    ["我的", "wǒ de", "my", "saya punya"],
    ["父亲", "fù qīn", "father", "bapa / ayah"],
    ["很", "hěn", "very", "sangat"],
    ["疼", "téng", "love / dote on", "sayang"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but / however", "tetapi"],
    ["他", "tā", "he", "dia"],
    ["管教", "guǎn jiào", "discipline / manage", "mendidik / mengajar"],
    ["我", "wǒ", "me", "saya"],
    ["很", "hěn", "very", "sangat"],
    ["严", "yán", "strict", "tegas / ketat"],
    ["，", "", "", ""],
    ["很", "hěn", "very", "sangat"],
    ["严", "yán", "strict", "tegas / ketat"],
    ["很", "hěn", "very", "sangat"],
    ["严", "yán", "strict", "tegas / ketat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["当", "dāng", "when", "apabila / tatkala"],
    ["我", "wǒ", "I", "saya"],
    ["上", "shàng", "attend / go to", "pergi ke"],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["的", "de", "particle", "yang"],
    ["时候", "shí hou", "time / period", "masa / waktu"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["早晨", "zǎo chén", "morning", "pagi"],
    ["醒来", "xǐng lái", "wake up", "bangun tidur"],
    ["，", "", "", ""],
    ["只要", "zhǐ yào", "as long as / if only", "asalkan / sekiranya"],
    ["听见", "tīng jiàn", "hear", "mendengar"],
    ["窗外", "chuāng wài", "outside the window", "di luar tingkap"],
    ["哗啦啦", "huā lā lā", "pattering (sound of rain)", "bunyi deruan air / hujan lebat"],
    ["下着", "xià zhe", "raining", "sedang turun"],
    ["大雨", "dà yǔ", "heavy rain", "hujan lebat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["心里", "xīn lǐ", "in the heart / mentally", "dalam hati"],
    ["就", "jiù", "then", "pun / terus"],
    ["会", "huì", "will", "akan"],
    ["好老大", "hǎo lǎo dà", "greatly / very much", "sangat / tersangat"],
    ["的", "de", "particle", ""],
    ["不高兴", "bù gāo xìng", "unhappy / displeased", "tidak gembira / kesal"],
    ["，", "", "", ""],
    ["觉得", "jué de", "feel / think", "berasa / rasa"],
    ["上学", "shàng xué", "go to school", "pergi ke sekolah"],
    ["是", "shì", "is", "adalah"],
    ["一件", "yí jiàn", "a (measure word for matters)", "satu (penjodoh bilangan)"],
    ["极为", "jí wéi", "extremely", "amat / sangat"],
    ["痛苦", "tòng kǔ", "painful / miserable", "perit / menyakitkan"],
    ["的", "de", "particle", "yang"],
    ["事", "shì", "matter / thing", "perkara"],
    ["。", "", "", ""],
    ["常常", "cháng cháng", "often / frequently", "selalu / kerap kali"],
    ["到", "dào", "until", "sehingga"],
    ["了", "le", "particle", ""],
    ["时间", "shí jiān", "time", "masa"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["还", "hái", "still", "masih"],
    ["赖在", "lài zài", "loiter / lounge on", "terbaring / melekat di"],
    ["床上", "chuáng shàng", "on the bed", "atas katil"],
    ["不肯", "bù kěn", "unwilling to", "tidak mahu / enggan"],
    ["起来", "qǐ lái", "get up", "bangun"],
    ["。", "", "", ""],
    ["这时候", "zhè shí hou", "at this moment", "pada waktu ini"],
    ["，", "", "", ""],
    ["我就", "wǒ jiù", "I then", "saya pun"],
    ["会", "huì", "will", "akan"],
    ["怀着", "huái zhe", "harbor / full of", "membawa / dengan rasa"],
    ["恐惧", "kǒng jù", "fear / dread", "takut / cemas"],
    ["的", "de", "particle", "yang"],
    ["心情", "xīn qíng", "mood / state of mind", "perasaan / hati"],
    ["想", "xiǎng", "think about", "memikirkan"],
    ["：", "", "", ""],
    ["准", "zhǔn", "certainly / for sure", "pasti / tentu"],
    ["又是", "yòu shì", "again is", "sekali lagi adalah"],
    ["一", "yī", "once (short for 一进)", "sebaik saja"],
    ["进", "jìn", "enter", "masuk"],
    ["教室", "jiào shì", "classroom", "bilik darjah"],
    ["就", "jiù", "then", "pun"],
    ["被", "bèi", "by (passive)", "di- / oleh"],
    ["罚站", "fá zhàn", "punished to stand", "didenda berdiri"],
    ["在", "zài", "at", "di"],
    ["门边", "mén biān", "by the door", "tepi pintu"],
    ["，", "", "", ""],
    ["同学们的", "tóng xué men de", "classmates'", "rakan-rakan sekelas punya"],
    ["眼光", "yǎn guāng", "gaze / looks", "pandangan mata"],
    ["会", "huì", "will", "akan"],
    ["一个个", "yí gè gè", "one by one", "satu demi satu"],
    ["投过来", "tóu guò lái", "cast over / look towards", "dilemparkan ke arah saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["很", "hěn", "very", "sangat"],
    ["懒惰", "lǎn duò", "lazy", "malas"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi / namun"],
    ["也", "yě", "also", "juga"],
    ["知道", "zhī dào", "know", "tahu"],
    ["害羞", "hài xiū", "shy / feel ashamed", "malu"],
    ["呀", "ya", "particle", "lah"],
    ["！", "", "", ""],
    ["更", "gèng", "even more", "lagi / lebih-lebih lagi"],
    ["糟糕", "zāo gāo", "terrible / bad", "teruk / dahsyat"],
    ["的", "de", "particle", "yang"],
    ["是", "shì", "is", "adalah"],
    ["，", "", "", ""],
    ["爸爸是", "bà ba shì", "father is", "ayah adalah"],
    ["不许", "bù xǔ", "not allow", "tidak membenarkan"],
    ["小孩子", "xiǎo hái zi", "children", "kanak-kanak"],
    ["上学", "shàng xué", "go to school", "pergi ke sekolah"],
    ["乘车", "chéng chē", "ride in a car / vehicle", "naik kenderaan"],
    ["的", "de", "particle", ""],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["不管", "bù guǎn", "no matter / regardless of", "tidak peduli / tidak kira"],
    ["你", "nǐ", "you", "kamu"],
    ["晚不晚", "wǎn bù wǎn", "late or not", "lewat atau tidak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["有一个", "yǒu yí gè", "there is a", "ada satu"],
    ["下雨天", "xià yǔ tiān", "rainy day", "hari hujan"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah / telah"],
    ["过", "guò", "past", "melepas / lewat"],
    ["了", "le", "particle", ""],
    ["醒来", "xǐng lái", "wake up", "bangun"],
    ["的", "de", "particle", "yang"],
    ["时间", "shí jiān", "time", "masa"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["惧怕", "jù pà", "fear / dread", "takut akan / gerun"],
    ["去", "qù", "go to", "pergi ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["，", "", "", ""],
    ["竟然", "jìng rán", "unexpectedly / audacious enough to", "secara tidak jangka / berani pula"],
    ["很", "hěn", "very", "sangat"],
    ["勇敢", "yǒng gǎn", "bravely", "berani / dengan berani"],
    ["地", "de", "particle", "dengan"],
    ["赖在", "lài zài", "loiter / stay stubbornly", "melekat di / terus berbaring di"],
    ["床上", "chuāng shàng", "on the bed", "atas katil"],
    ["不起来", "bù qǐ lái", "not getting up", "tidak bangun"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["等", "děng", "wait until", "tunggu sampai"],
    ["到", "dào", "arrive", "tiba"],
    ["爸爸", "bà ba", "father", "ayah"],
    ["进门", "jìn mén", "enter the room / door", "masuk pintu"],
    ["来", "lái", "come", "datang"],
    ["催促", "cuī cù", "urge / hurry someone", "menggesa / mendesak"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["依然", "yī rán", "still / as before", "masih / tetap"],
    ["找借口", "zhǎo jiè kǒu", "make excuses", "mencari alasan"],
    ["说", "shuō", "say", "berkata"],
    ["雨", "yǔ", "rain", "hujan"],
    ["下得", "xià de", "falling (with description)", "turun dengan"],
    ["太大了", "tài dà le", "too big / heavy", "terlalu lebat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不想", "bù xiǎng", "don't want to", "tidak mahu"],
    ["去", "qù", "go", "pergi"],
    ["了", "le", "particle", ""],
    ["生活", "shēng huó", "life (here it means contextually target/excuse)", "kehidupan (konteks: alasan)"],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "father", "Ayah"],
    ["顿时", "dùn shí", "instantly / immediately", "serta-merta / serta menteri"],
    ["火冒三丈", "huǒ mào sān zhàng", "furious / fly into a rage", "sangat marah / naik radang"],
    ["，", "", "", ""],
    ["一把", "yì bǎ", "grab (measure word for action)", "sentap / terus (tindakan tangkas)"],
    ["把我", "bǎ wǒ", "object particle (me)", "menarik saya"],
    ["从", "cóng", "from", "dari"],
    ["被窝", "bèi wō", "quilt / blanket", "bawah selimut"],
    ["里", "lǐ", "inside", "dalam"],
    ["扯了", "chě le", "dragged / pulled", "rentap / tarik keluar"],
    ["出来", "chū lái", "out", "keluar"],
    ["，", "", "", ""],
    ["拿起", "ná qǐ", "picked up", "mengambil / memegang"],
    ["鸡毛掸子", "jī máo dǎn zi", "feather duster", "penyapu bulu ayam"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["床头", "chuáng tóu", "head of the bed", "kepala katil"],
    ["狠狠", "hěn hěn", "severely / fiercely", "dengan updates / cukup kuat"],
    ["地", "de", "particle", ""],
    ["打了", "dǎ le", "beat / whipped", "memukul / membelas"],
    ["我", "wǒ", "me", "saya"],
    ["一顿", "yí dùn", "a round (measure word for scolding/beating)", "sekali / satu pusingan"],
    ["，", "", "", ""],
    ["直到", "zhí dào", "until", "sehingga"],
    ["把我", "bǎ wǒ", "object particle (me)", "saya"],
    ["从", "cóng", "from", "dari"],
    ["床头", "chuáng tóu", "head of bed", "kepala katil"],
    ["打到", "dǎ dào", "beat until / to", "dihambat sampai ke"],
    ["了", "le", "particle", ""],
    ["床尾", "chuáng wěi", "foot of the bed", "hujung katil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["最后", "zuì hòu", "finally / in the end", "Akhirnya"],
    ["我", "wǒ", "I", "saya"],
    ["还是", "hái shì", "still", "tetap / juga"],
    ["哭着", "kū zhe", "crying", "dengan menangis / sambil menangis"],
    ["穿好", "chuān hǎo", "dressed up properly", "memakai dengan rapi"],
    ["衣服", "yī fu", "clothes", "pakaian / baju"],
    ["，", "", "", ""],
    ["背上", "bēi shàng", "put on back", "menggalas"],
    ["书包", "shū bāo", "school bag", "beg sekolah"],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "father", "Ayah"],
    ["冷冷", "lěng lěng", "coldly", "dengan dingin / tegas"],
    ["地", "de", "particle", ""],
    ["命令", "mìng lìng", "ordered / commanded", "memerintah / mengarah"],
    ["我", "wǒ", "me", "saya"],
    ["道", "dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["怎么", "zěn me", "how / why", "bagaimana / kenapa"],
    ["可以", "kě yǐ", "can / allowed to", "boleh"],
    ["逃学", "táo xué", "play truant / skip school", "ponteng sekolah"],
    ["？", "", "", ""],
    ["给我", "gěi wǒ", "give me (here it means emphasis command)", "pergi / kamu mesti"],
    ["走", "zǒu", "go / walk", "pergi / jalan"],
    ["去", "qù", "to (direction)", "ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["妈妈", "mā ma", "mother", "Emak / ibu"],
    ["在", "zài", "at", "di"],
    ["一旁", "yì páng", "aside / nearby", "tepi / sebelah"],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["心疼", "xīn téng", "distressed / feel sorry for", "merasa kasihan / pilu hati"],
    ["不已", "bù yǐ", "endlessly", "tidak terhenti-henti / teramat sangat"],
    ["，", "", "", ""],
    ["悄悄", "qiāo qiāo", "quietly / secretly", "secara senyap-senyap"],
    ["地", "de", "particle", ""],
    ["塞给", "sāi gěi", "stuffed into / handed over stealthily", "menyelitkan kepada / menghulurkan senyap-senyap"],
    ["了", "le", "particle", ""],
    ["我", "wǒ", "me", "saya"],
    ["五个", "wǔ gè", "five", "lima keping"],
    ["铜板", "tóng bǎn", "copper coins", "duit syiling gangsa"],
    ["，", "", "", ""],
    ["让", "ràng", "let / allow", "menyuruh / membenarkan"],
    ["我", "wǒ", "me", "saya"],
    ["去", "qù", "go to", "pergi"],
    ["乘", "chéng", "ride / take", "naik"],
    ["三轮车", "sān lún chē", "tricycle / pedicab", "beca"],
    ["上学", "shàng xué", "go to school", "pergi sekolah"],
    ["，", "", "", ""],
    ["免得", "miǎn de", "so as not to / avoid", "supaya tidak / elok elok"],
    ["迟到", "chí dào", "be late", "lewat / lambat"],
    ["得", "de", "particle", ""],
    ["太久", "tài jiǔ", "too long", "terlalu lama"],
    ["了", "le", "particle", ""],
    ["处理", "chǔ lǐ", "handle (here part of phrase or standalone particle)", "menguruskan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["我", "wǒ", "I", "Saya"],
    ["坐在", "zuò zài", "sitting in / on", "duduk di dalam"],
    ["三轮车", "sān lún chē", "pedicab / tricycle", "beca"],
    ["上", "shàng", "on", "atas / dalam"],
    ["，", "", "", ""],
    ["一边", "yì biān", "whilst / at the same time", "sambil"],
    ["抹着", "mǒ zhe", "wiping", "menyapu / mengesat"],
    ["眼泪", "yǎn lèi", "tears", "air mata"],
    ["，", "", "", ""],
    ["一边", "yì biān", "whilst", "sambil"],
    ["拼命", "pīn mìng", "desperately / with all might", "bermati-matian / sekuat hati"],
    ["地", "de", "particle", ""],
    ["把", "bǎ", "structural particle", ""],
    ["裙子", "qún zi", "skirt", "kain rok / skirt"],
    ["向下拉了拉", "xiàng xià lā le lā", "pulled down repeatedly", "menarik-narik ke bawah"],
    ["，", "", "", ""],
    ["试图", "shì tú", "attempt / try to", "cuba / cuba untuk"],
    ["遮掩", "zhē yǎn", "cover up / hide", "menyembunyikan / menutup"],
    ["脚上", "jiǎo shàng", "on the legs / feet", "pada kaki"],
    ["那", "nà", "those", "itu"],
    ["一条条", "yì tiáo tiáo", "row of (measure word for stripes/marks)", "berjalur-jalur / kesan panjang"],
    ["被", "bèi", "by (passive)", "di-"],
    ["爸爸", "bà ba", "father", "ayah"],
    ["抽出来", "chōu chū lái", "whipped out (stripes/marks)", "sebat (kesan lebam sebat)"],
    ["的", "de", "particle", "yang"],
    ["红肿", "hóng zhǒng", "red and swollen", "merah dan bengkak"],
    ["伤痕", "shāng hén", "scars / bruises", "kesan luka / lebam"],
    ["，", "", "", ""],
    ["心里", "xīn lǐ", "in the heart", "dalam hati"],
    ["充满了", "chōng mǎn le", "filled with", "penuh dengan / sarat dengan"],
    ["对", "duì", "towards", "terhadap"],
    ["爸爸的", "bà ba de", "father's", "ayah punya"],
    ["怨恨", "yuàn hèn", "resentment / grudge", "perasaan dendam / benci"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["好不容易", "hǎo bù róng yì", "with great difficulty", "dengan bersusah payah"],
    ["赶到", "gǎn dào", "rushed to", "sampai ke / bergegas tiba di"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["，", "", "", ""],
    ["万幸", "wàn xìng", "extremely lucky", "tersangat beruntung / mujur"],
    ["的", "de", "particle", ""],
    ["是", "shì", "is", "adalah"],
    ["，", "", "", ""],
    ["第一节", "dì yī jié", "the first period / class", "waktu pelajaran pertama"],
    ["课", "kè", "lesson / class", "kelas / matapelajaran"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["还没", "hái méi", "not yet", "belum lagi"],
    ["到", "dào", "arrive", "tiba"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["赶紧", "gǎn jǐn", "hurriedly", "segera / dengan cepat"],
    ["溜进", "liū jìn", "sneaked into", "menyelinap masuk ke"],
    ["座位", "zuò wèi", "seat", "tempat duduk"],
    ["，", "", "", ""],
    ["心", "xīn", "heart", "hati"],
    ["才", "cái", "only then", "barulah"],
    ["稍微", "shāo wēi", "slightly / a bit", "sedikit / agak"],
    ["安定", "ān dìng", "settled / calm", "tenang / tenteram"],
    ["了", "le", "particle", ""],
    ["一些", "yì xiē", "a little", "sedikit"],
    ["拓展", "tuò zhǎn", "expand / stand (contextual particle placeholder)", "berkembang (placeholder)"],
    ["下", "xià", "down / bit", "sedikit"],
    ["去", "qù", "go", "pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["过", "guò", "past / after", "Selepas / setelah"],
    ["了一会儿", "le yí huì r", "a little while", "sekejap / seketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["无意间", "wú yì jiān", "inadvertently / accidentally", "secara tidak sengaja / terserempak"],
    ["向", "xiàng", "towards", "ke arah"],
    ["窗外", "chuāng wài", "outside the window", "luar tingkap"],
    ["一望", "yí wàng", "took a glance", "memandang sekilas"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["发现", "fā xiàn", "spotted / found", "ternampak / mendapati"],
    ["外面的", "wài mian de", "outside's", "keadaan di luar punya"],
    ["走廊", "zǒu láng", "corridor", "koridor / kaki lima"],
    ["上", "shàng", "on", "atas / di"],
    ["，", "", "", ""],
    ["竟然", "jìng rán", "unexpectedly", "rupa-rupanya / secara tidak sangka"],
    ["站着", "zhàn zhe", "standing", "sedang berdiri"],
    ["一个", "yí gè", "a", "seorang"],
    ["熟悉", "shú xī", "familiar", "yang biasa dikenali"],
    ["的", "de", "particle", "yang"],
    ["高大", "gāo dà", "tall and big", "tinggi lampai / besar"],
    ["影子", "yǐng zi", "shadow / figure", "kelibat / bayangan"],
    ["——", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["正是", "zhèng shì", "exactly is", "memang adalah / tidak lain bukan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["父亲", "fù qīn", "father", "ayah"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["刚", "gāng", "just", "baru sahaja"],
    ["安静", "ān jìng", "quiet / calm", "tenang"],
    ["下来", "xià lái", "down", "semula"],
    ["的", "de", "particle", ""],
    ["心", "xīn", "heart", "hati"],
    ["，", "", "", ""],
    ["顿时", "dùn shí", "instantly", "serta-merta"],
    ["又", "yòu", "again", "pula / sekali lagi"],
    ["再次", "zài cì", "once more", "kembali"],
    ["剧烈", "jù liè", "intensely / violently", "dengan kencang / kuat"],
    ["地", "de", "particle", ""],
    ["波动", "bō dòng", "fluctuated / fluttered", "berdebar-debar / bergelora"],
    ["起来", "qǐ lái", "up", "semula"],
    ["，", "", "", ""],
    ["充满", "chōng mǎn", "filled with", "sarat / penuh dengan"],
    ["了", "le", "particle", ""],
    ["不安", "bù ān", "uneasiness / anxiety", "rasa tidak tenang / gelisah"],
    ["与", "yǔ", "and", "dan"],
    ["害怕", "hài pà", "fear", "takut"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["只见", "zhǐ jiàn", "only saw", "Hanya kelihatan"],
    ["爸爸", "bà ba", "father", "ayah"],
    ["手里", "shǒu lǐ", "in the hand", "di tangan"],
    ["抱着", "bào zhe", "holding / carrying", "memeluk / memegang"],
    ["一件", "yí jiàn", "a (measure word for clothing)", "sehelai"],
    ["花夹袄", "huā jiá ǎo", "lined jacket / floral jacket", "baju sejuk bercorak bunga / jaket"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["是", "shì", "is", "adalah"],
    ["出门", "chū mén", "go out", "keluar rumah"],
    ["前", "qián", "before", "sebelum"],
    ["妈妈", "mā ma", "mother", "emak"],
    ["特意", "tè yì", "specially / deliberately", "sengaja / khas"],
    ["为我", "wèi wǒ", "for me", "untuk saya"],
    ["准备", "zhǔn bèi", "prepared", "sediakan"],
    ["防寒", "fáng hán", "protect against cold", "menahan sejuk"],
    ["的", "de", "particle", ""],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "father", "Ayah"],
    ["缓缓", "huǎn huǎn", "slowly", "perlahan-lahan / dengan lambat"],
    ["走到", "zǒu dào", "walked to", "berjalan ke"],
    ["教室", "jiào shì", "classroom", "bilik darjah"],
    ["门口", "mén kǒu", "doorway / entrance", "pintu masuk"],
    ["，", "", "", ""],
    ["向", "xiàng", "towards", "kepada"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["微微", "wēi wēi", "slightly / faintly", "sedikit / sedikit mengangguk"],
    ["点头", "diǎn tóu", "nodded head", "mengangguk kepala"],
    ["示意", "shì yì", "signalled / gestured", "memberi isyarat"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["把", "bǎ", "structural particle", ""],
    ["我", "wǒ", "me", "saya"],
    ["叫了", "jiào le", "called", "memanggil"],
    ["出去", "chū qù", "out", "keluar"],
    ["处理", "chǔ lǐ", "handle (placeholder particle)", "menguruskan"],
    ["关系", "guān xi", "relationship / context (placeholder)", "hubungan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["爸爸", "bà ba", "father", "Ayah"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["再", "zài", "again", "lagi"],
    ["厉声", "lì shēng", "sternly / harshly (voice)", "dengan suara keras / tengking"],
    ["责备", "zé bèi", "scold / reproach", "memarahi / menyelar"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "just / only", "hanya / sekadar"],
    ["把", "bǎ", "structural particle", ""],
    ["花夹袄", "huā jiá ǎo", "floral jacket", "baju sejuk bercorak bunga"],
    ["轻轻", "qīng qīng", "gently / softly", "dengan lembut"],
    ["地", "de", "particle", ""],
    ["披在", "pī zài", "draped over", "menyelimutkan pada / menyarungkan ke atas"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["肩上", "jiān shàng", "shoulders", "bahu"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["从", "cóng", "from", "dari"],
    ["口袋", "kǒu dài", "pocket", "poket / kocek baju"],
    ["里", "lǐ", "inside", "dalam"],
    ["摸出", "mō chū", "fumbled out / took out", "mengeluarkan / menyeluk keluar"],
    ["了", "le", "particle", ""],
    ["两个", "liǎng gè", "two", "dua keping"],
    ["铜板", "tóng bǎn", "copper coins", "duit syiling gangsa"],
    ["，", "", "", ""],
    ["塞到", "sāi dào", "stuffed into / handed to", "menyelitkan ke dalam / menghulurkan ke"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["，", "", "", ""],
    ["低声", "dī shēng", "in a low voice", "dengan suara perlahan / berbisik"],
    ["说道", "shuō dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["拿着", "ná zhe", "hold it / take it", "Ambil ini"],
    ["，", "", "", ""],
    ["放学", "fàng xué", "after school", "balik sekolah / selesai kelas"],
    ["回家", "huí jiā", "go home", "balik rumah"],
    ["时", "shí", "when", "nanti / apabila"],
    ["坐车", "zuò chē", "take a vehicle / car", "naik kenderaan"],
    ["用", "yòng", "use", "gunakan"],
    ["吧", "ba", "particle", "lah"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["说完", "shuō wán", "finished speaking", "Selesai bercakap"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["便", "biàn", "then / straightaway", "pun / lalu"],
    ["转过身", "zhuǎn guò shēn", "turned body around", "memusingkan badan / berpaling"],
    ["，", "", "", ""],
    ["冒着", "mào zhe", "braving (the rain)", "mengharungi / meredah"],
    ["外面", "wài mian", "outside's", "luar punya"],
    ["漫天", "màn tiān", "filling the whole sky", "seluruh langit / lebat"],
    ["的", "de", "particle", "yang"],
    ["风雨", "fēng yǔ", "wind and rain", "ribut hujan / angin dan hujan"],
    ["，", "", "", ""],
    ["快步", "kuài bù", "stride / quickly steps", "dengan langkah cepat"],
    ["走下", "zǒu xià", "walked down", "berjalan turun"],
    ["台阶", "tái jiē", "steps / stairs", "anak tangga"],
    ["，", "", "", ""],
    ["离去", "lí qù", "left / departed", "pergi / berlalu"],
    ["了", "le", "particle", ""],
    ["布局", "bù jú", "layout / arrangement (placeholder)", "susunan"],
    ["布局", "bù jú", "layout (placeholder)", "susunan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["看着", "kàn zhe", "Watching / looking at", "Melihat"],
    ["父亲", "fù qīn", "father", "bapa / ayah"],
    ["在", "zài", "in", "dalam"],
    ["雨中", "yǔ zhōng", "rain", "hujan"],
    ["渐渐", "jiàn jiàn", "gradually", "lama-kelamaan / beransur-ansur"],
    ["远去", "yuǎn qù", "fading away / distance", "menjauh pergi"],
    ["的", "de", "particle", "yang"],
    ["背影", "bèi yǐng", "view of someone's back", "pandangan belakang / susuk belakang"],
    ["，", "", "", ""],
    ["摸着", "mō zhe", "touching / feeling", "memegang / meraba"],
    ["手里", "shǒu lǐ", "in hand", "di tangan"],
    ["那", "nà", "those", "itu"],
    ["带着", "dài zhe", "carrying / with", "membawa / yang ada"],
    ["父亲", "fù qīn", "father's", "ayah punya"],
    ["体温", "tǐ wēn", "body temperature", "suhu badan"],
    ["的", "de", "particle", "yang"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["铜板", "tóng bǎn", "copper coins", "duit syiling gangsa"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["再次", "zài cì", "once again", "sekali lagi"],
    ["夺眶而出", "duó kuàng ér chū", "burst into tears / gush out", "mengalir keluar dengan deras / berhamburan"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "only this time", "cuma kali ini"],
    ["这一次", "zhè yí cì", "this time", "kali ini"],
    ["，", "", "", ""],
    ["心中", "xīn zhōng", "in the heart", "dalam hati"],
    ["不再是", "bú zhài shì", "no longer is", "bukan lagi"],
    ["怨恨", "yuàn hèn", "resentment / hatred", "dendam / benci"],
    ["，", "", "", ""],
    ["而是", "ér shì", "but rather", "sebaliknya adalah / melainkan"],
    ["满满的", "mǎn mǎn de", "full of", "penuh dengan"],
    ["懊悔", "ào huǐ", "remorse / regret", "penyesalan / rasa bersalah"],
    ["与", "yǔ", "and", "dan"],
    ["感动", "gǎn dòng", "moved / touched", "terharu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["从那以后", "cóng nà yǐ hòu", "From then on", "Sejak daripada itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["早晨", "zǎo chén", "morning", "pagi"],
    ["都", "dōu", "all / always", "pun / pasti"],
    ["早早", "zǎo zǎo", "very early", "sangat awal"],
    ["起床", "qǐ chuáng", "get out of bed", "bangun daripada tidur"],
    ["，", "", "", ""],
    ["再也", "zài yě", "never again", "tidak pernah lagi"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["赖过床", "lài guò chuáng", "loitered in bed", "berbaring malas di katil / sun-down"],
    ["。", "", "", ""],
    ["每天", "měi tiān", "Every day", "Setiap hari"],
    ["早晨", "zǎo chén", "morning", "pagi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["都", "dōu", "all / always", "pasti / sentiasa"],
    ["是", "shì", "am", "adalah"],
    ["第一个", "dì yī gè", "the first one", "orang pertama"],
    ["站在", "zhàn zài", "standing at", "berdiri di"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["门口", "mén kǒu", "gate / entrance", "pintu pagar / pintu masuk"],
    ["，", "", "", ""],
    ["静静", "jìng jìng", "quietly", "dengan senyap / tenang"],
    ["等待着", "děng dài zhe", "waiting for", "menunggu"],
    ["校工", "xiào gōng", "school janitor / worker", "pekerja sekolah / pak jaga"],
    ["打开", "dǎ kāi", "open", "membuka"],
    ["那扇", "nà shàn", "that (measure word for door/gate)", "pintu pagar (penjodoh bilangan)"],
    ["学校", "xué xiào", "school's", "sekolah punya"],
    ["大铁栅", "dà tiě zhà", "large iron gate", "pintu pagar besi besar"],
    ["的", "de", "particle", "yang"],
    ["学生", "xué shēng", "student", "murid / pelajar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 分段标记，切入文末作者出处

    // 文末作者出处
    ["（", "", "", ""],
    ["林海音", "lín hǎi yīn", "Lin Hai-yin (Author)", "Lin Hai-yin (Penulis)"],
    ["《", "", "", ""],
    ["迟到", "chí dào", "Late", "Lewat"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with / has", "ada"],
    ["改动", "gǎi dòng", "adaptations / modifications", "ubah suai / perubahan"],
    ["）", "", "", ""]
];
