const lessonTitle = "迟到";

const lessonData = [
    // 正文第 1 段
    ["我的", "wǒ de", "my", "saya punya"],
    ["父亲", "fù qīn", "father", "bapa / ayah"],
    ["很", "hěn", "very", "sangat / amat"],
    ["疼", "téng", "love dearly / dote on", "sayang / mengasihi"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but / however", "tetapi / namun"],
    ["他", "tā", "he / him", "dia"],
    ["管教", "guǎn jiào", "discipline / teach", "mendisiplinkan / mengajar"],
    ["我", "wǒ", "me", "saya"],
    ["很", "hěn", "very", "sangat"],
    ["严", "yán", "strict", "tegas / garang"],
    ["，", "", "", ""],
    ["很严", "hěn yán", "very strict", "sangat tegas"],
    ["很严", "hěn yán", "very strict", "sangat tegas"],
    ["。", "", "", ""],
    ["有", "yǒu", "there is / have", "ada"],
    ["一件事", "yí jiàn shì", "one thing / an incident", "satu perkara / peristiwa"],
    ["我", "wǒ", "I", "saya"],
    ["永远", "yǒng yuǎn", "forever", "selama-lamanya / sampai bila-bila"],
    ["忘不了", "wàng bù liǎo", "cannot forget", "tidak dapat melupakan"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["当", "dāng", "when", "apabila / ketika"],
    ["我在", "wǒ zài", "I was in", "saya berada di"],
    ["一年级", "yī nián jí", "First Grade / Primary 1", "Tahun 1 / Darjah 1"],
    ["的", "de", "particle", "yang"],
    ["时候", "shí hou", "time", "masa / sewaktu"],
    ["，", "", "", ""],
    ["就", "jiù", "already / then", "pun / telah"],
    ["有", "yǒu", "had / have", "ada / mempunyai"],
    ["早晨", "zǎo chén", "morning", "pagi / awal pagi"],
    ["赖", "lài", "lounge / loiter", "bermalas-malasan / enggan bangun"],
    ["在", "zài", "on", "di / atas"],
    ["床上", "chuáng shàng", "bed", "atas katil"],
    ["不起来", "bù qǐ lái", "not getting up", "tidak bangun"],
    ["的", "de", "particle", "punya"],
    ["毛病", "máo bìng", "bad habit / flaw", "tabiat buruk / kelemahan"],
    ["。", "", "", ""],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["早晨", "zǎo chén", "morning", "pagi"],
    ["醒来", "xǐng lái", "wake up", "sedar / terjaga dari tidur"],
    ["，", "", "", ""],
    ["看到", "kàn dào", "see", "melihat / nampak"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["照到", "zhào dào", "shine upon", "menyinari / memancar ke"],
    ["玻璃窗", "bō li chuāng", "glass window", "tingkap kaca"],
    ["上", "shàng", "on", "atas"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["心里", "xīn lǐ", "in the heart / mind", "dalam hati / sanubari"],
    ["就是", "jiù shì", "exactly is / just", "hanyalah / adalah"],
    ["一阵", "yí zhèn", "a burst of / a fit of", "seketika / seketika perasaan"],
    ["愁", "chóu", "worry / anxiety", "bimbang / risau / gundah"],
    ["。", "", "", ""],
    ["心想", "xīn xiǎng", "think to oneself", "berfikir dalam hati"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah / telah"],
    ["这么", "zhè me", "so / this (late)", "begitu / sebegini"],
    ["晚", "wǎn", "late", "lewat"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["等", "děng", "wait till / after", "tunggu sehingga / selepas"],
    ["起来", "qǐ lái", "get up", "bangun"],
    ["洗脸", "xǐ liǎn", "wash face", "basuh muka"],
    ["、", "", "", ""],
    ["梳头", "shū tóu", "comb hair", "menyikat rambut"],
    ["、", "", "", ""],
    ["换", "huàn", "change", "tukar / menukar"],
    ["制服", "zhì fú", "uniform", "pakaian seragam"],
    ["，", "", "", ""],
    ["再", "zài", "then", "kemudian / baru"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["去", "qù", "go", "pergi"],
    ["，", "", "", ""],
    ["准", "zhǔn", "certainly / for sure", "pasti / tentu"],
    ["又", "yòu", "again", "lagi / pula"],
    ["是", "shì", "is", "adalah"],
    ["一", "yī", "as soon as", "sebaik sahaja"],
    ["进", "jìn", "enter", "masuk"],
    ["教室", "jiào shì", "classroom", "bilik darjah / kelas"],
    ["就", "jiù", "then", "terus / pun"],
    ["被", "bèi", "by (passive particle)", "di- / kena"],
    ["罚站", "fá zhàn", "punished by standing", "didenda berdiri"],
    ["在", "zài", "at", "di"],
    ["门边", "mén biān", "by the door", "tepi pintu"],
    ["，", "", "", ""],
    ["同学们", "tóng xué men", "classmates", "rakan-rakan sekelas"],
    ["的", "de", "particle", "punya"],
    ["眼光", "yǎn guāng", "gazes / looks", "pandangan mata / sorotan mata"],
    ["会", "huì", "will", "akan"],
    ["一个个", "yí gè gè", "one by one", "satu demi satu"],
    ["投过来", "tóu guò lái", "cast towards me", "dilemparkan ke arah saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["虽然", "suī rān", "although", "walaupun"],
    ["很", "hěn", "very", "sangat"],
    ["懒惰", "lǎn duò", "lazy", "malas"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi / namun"],
    ["也", "yě", "also", "juga"],
    ["知道", "zhī dào", "know", "tahu"],
    ["害羞", "hài xiū", "shy / ashamed", "malu / berasa malu"],
    ["呀", "ya", "particle", "lah / ya"],
    ["！", "", "", ""],
    ["所以", "suǒ yǐ", "therefore", "oleh itu / jadi"],
    ["又", "yòu", "both... (worry)", "sekaligus (risau)"],
    ["愁", "chóu", "worried", "gundah"],
    ["又", "yòu", "and (scared)", "dan (takut)"],
    ["怕", "pà", "scared", "takut"],
    ["，", "", "", ""],
    ["常常", "cháng cháng", "often", "sering kali / selalu"],
    ["都是", "dōu shì", "all were", "semestinya / sentiasa"],
    ["怀着", "huái zhe", "harboring / with (mood)", "membawa / diselubungi (perasaan)"],
    ["恐惧", "kǒng jù", "fear / dread", "ketakutan / kebimbangan"],
    ["的", "de", "particle", "yang"],
    ["心情", "xīn qíng", "mood / state of mind", "perasaan / suasana hati"],
    ["，", "", "", ""],
    ["奔向", "bēn xiàng", "dash towards", "berlari menuju ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["去", "qù", "go", "pergi"],
    ["。", "", "", ""],
    ["最糟", "zuì zāo", "the worst thing", "perkara paling buruk / malang"],
    ["的", "de", "particle", "yang"],
    ["是", "shì", "is", "adalah"],
    ["，", "", "", ""],
    ["爸爸", "bà ba", "father / dad", "bapa / ayah"],
    ["是", "shì", "is", "adalah"],
    ["不许", "bù xǔ", "not allow / forbid", "tidak membenarkan / melarang"],
    ["小孩子", "xiǎo hái zi", "children", "kanak-kanak / anak kecil"],
    ["上学", "shàng xué", "go to school", "pergi ke sekolah"],
    ["乘车", "chéng chē", "ride in a vehicle", "naik kenderaan"],
    ["的", "de", "particle", ""],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["不管", "bù guǎn", "no matter / regardless of", "tidak peduli / tidak menghiraukan sama ada"],
    ["你", "nǐ", "you", "kamu"],
    ["晚不晚", "wǎn bù wǎn", "late or not", "lewat atau tidak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["有一天", "yǒu yì tiān", "one day", "Pada suatu hari"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari / sejak"],
    ["早晨", "zǎo chén", "morning", "pagi"],
    ["起", "qǐ", "starting from", "mula"],
    ["就", "jiù", "then", "pun"],
    ["下大雨", "xià dà yǔ", "rain heavily", "hujan lebat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["醒来", "xǐng lái", "woke up", "terjaga"],
    ["就", "jiù", "then", "terus"],
    ["知道", "zhī dào", "knew", "tahu"],
    ["不早了", "bù zǎo le", "not early / late", "sudah lewat / bukan awal lagi"],
    ["，", "", "", ""],
    ["听着", "tīng zhe", "listening to", "mendengar"],
    ["不停", "bù tíng", "ceaselessly / non-stop", "tanpa henti / mencurah-curah"],
    ["的", "de", "particle", "yang"],
    ["大雨", "dà yǔ", "heavy rain", "hujan lebat"],
    ["，", "", "", ""],
    ["心里", "in the heart", "dalam hati"],
    ["愁得不得了", "chóu de bù dé liǎo", "unbelievably worried", "risau yang teramat sangat"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["上学", "shàng xué", "go to school", "pergi sekolah"],
    ["不但", "bú dàn", "not only", "bukan sahaja"],
    ["要", "yào", "will / going to", "akan"],
    ["迟到了", "chí dào le", "be late", "lewat"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "but also / furthermore", "malah / lagipun"],
    ["在", "zài", "in / during", "pada / ketika"],
    ["夏天", "xià tiān", "summer", "musim panas"],
    ["的", "de", "particle", "yang"],
    ["时候", "shí hou", "time", "masa"],
    ["，", "", "", ""],
    ["还要", "hái yào", "still have to", "masih perlu"],
    ["被", "bèi", "by (passive)", "di- / oleh"],
    ["妈妈", "mā ma", "mother / mom", "emak / ibu"],
    ["打扮得", "dǎ bàn de", "dressed up as", "dihias / dipakaikan sehingga"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["肥大", "féi dà", "loose / oversized", "longgar / besar"],
    ["的", "de", "particle", "yang"],
    ["夹袄", "jiá ǎo", "lined jacket", "jaket berlapis / baju sejuk"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["举着", "jǔ zhe", "holding up", "memegang / mengangkat"],
    ["一把", "yì bǎ", "one (measure word for umbrella)", "sebumbung / sekaki"],
    ["大", "dà", "big", "besar"],
    ["油纸伞", "yóu zhǐ sǎn", "oil-paper umbrella", "payung kertas minyak"],
    ["，", "", "", ""],
    ["一路", "yí lù", "all the way", "sepanjang jalan"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["去", "qù", "go", "pergi"],
    ["。", "", "", ""],
    ["想到", "xiǎng dào", "thinking of", "memikirkan tentang"],
    ["这么", "zhè me", "so / such", "begitu / sebegini"],
    ["不舒服", "bù shū fu", "uncomfortable", "tidak selesa"],
    ["地", "de", "particle", "dengan"],
    ["上学", "shàng xué", "going to school", "pergi sekolah"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["竟", "jìng", "unexpectedly / actually", "malah / rupa-rupanya"],
    ["很", "hěn", "very", "sangat"],
    ["勇敢", "yǒng gǎn", "bravely / boldly", "berani / dengan berani"],
    ["地", "de", "particle", ""],
    ["赖", "lài", "lounge / lie", "berdegil / malas"],
    ["在", "zài", "on", "di atas"],
    ["床上", "chuáng shàng", "bed", "katil"],
    ["不起来了", "bù qǐ lái le", "refused to get up", "enggan bangun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["过了一会儿", "guò le yí huì r", "after a while", "Seketika kemudian / sekejap lagi"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "mother", "ibu"],
    ["进来", "jìn lái", "came in", "masuk ke dalam"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["她", "tā", "she", "Dia"],
    ["看", "kàn", "saw / looked", "melihat"],
    ["我", "wǒ", "me", "saya"],
    ["还没有", "hái méi yǒu", "still not yet", "masih belum"],
    ["起来", "qǐ lái", "get up", "bangun"],
    ["，", "", "", ""],
    ["吓了一跳", "xià le yí tiào", "startled / shocked", "terkejut"],
    ["，", "", "", ""],
    ["催促着", "cuī cù zhe", "hurrying / urging", "mendesak / menggesa"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "but", "Tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["皱紧了", "zhòu jǐn le", "furrowed tightly", "mengerutkan dengan rapat"],
    ["眉头", "méi tóu", "brows / forehead", "kening / dahi"],
    ["，", "", "", ""],
    ["低声", "dī shēng", "in a low voice", "dengan suara perlahan / berbisik"],
    ["向", "xiàng", "towards / to", "kepada"],
    ["妈妈", "mā ma", "mother", "ibu"],
    ["哀求", "āi qiú", "entreated / begged", "merayu / memohon"],
    ["说", "shuō", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["妈", "mā", "Mom", "Mak"],
    ["，", "", "", ""],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["晚了", "wǎn le", "late", "lewat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["就", "jiù", "then / just", "maka / tidak usah"],
    ["不要", "bú yào", "do not want / better not", "jangan / tidak usah"],
    ["去", "qù", "go to", "pergi"],
    ["上学", "shàng xué", "school", "sekolah"],
    ["了", "le", "particle", ""],
    ["吧", "ba", "particle (suggestion)", "lah / ya"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["妈妈", "mā ma", "mother", "Ibu"],
    ["就是", "jiù shì", "simply / exactly", "memang / hanyalah"],
    ["做不了主", "zuò bù liǎo zhǔ", "cannot make the decision", "tidak boleh membuat keputusan / tiada kuasa"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["她", "tā", "she", "dia"],
    ["转身", "zhuǎn shēn", "turned around", "memusingkan badan / berpaling"],
    ["出去", "chū qù", "go out", "keluar"],
    ["，", "", "", ""],
    ["爸爸", "bà ba", "father", "ayah"],
    ["就", "jiù", "then", "pun / terus"],
    ["进来了", "jìn lái le", "came in", "masuk"],
    ["处理", "", "", ""], // 补充逻辑平滑
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["站到", "zhàn dào", "stood by / reached", "berdiri di"],
    ["床前", "chuáng qián", "bedside", "depan katil"],
    ["，", "", "", ""],
    ["瞪着", "dèng zhe", "staring crossly at", "merenung tajam / membuntangkan mata kepada"],
    ["我", "wǒ", "me", "saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["怎么", "zěn me", "how come / why", "mengapa / kenapakah"],
    ["还", "hái", "still", "masih"],
    ["不", "bù", "not", "tidak"],
    ["起来", "qǐ lái", "get up", "bangun"],
    ["？", "", "", ""],
    ["快", "kuài", "quickly", "cepat / segeralah"],
    ["起来", "qǐ lái", "get up", "bangun"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["“", "", "", ""],
    ["晚了", "wǎn le", "It's late", "Sudah lewat"],
    ["，", "", "", ""],
    ["爸", "bà", "Dad", "ayah"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["硬着头皮", "yì zhe tóu pí", "braced myself / forced myself", "memberanikan diri / menebalkan muka"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["“", "", "", ""],
    ["晚", "wǎn", "Late", "Lewat"],
    ["也", "yě", "also", "pun"],
    ["得", "děi", "must / have to", "mesti / wajib"],
    ["去", "qù", "go", "pergi"],
    ["，", "", "", ""],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["可以", "kě yǐ", "can / allowed to", "boleh"],
    ["逃学", "táo xué", "truant / skip school", "ponteng sekolah"],
    ["？", "", "", ""],
    ["起", "qǐ", "Get up", "Bangun"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["一个字", "yí gè zì", "one single word", "Satu patah perkataan"],
    ["的", "de", "particle", "punya"],
    ["命令", "mìng lìng", "command / order", "perintah / arahan"],
    ["最", "zuì", "most", "paling"],
    ["可怕", "kě pà", "scary / terrifying", "menakutkan"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["怎么了", "zěn me le", "what's wrong with me", "entah kenapa / apa sudah jadi"],
    ["？", "", "", ""],
    ["居然", "jū rán", "unexpectedly / actually had", "secara tidak disangka / rupa-rupanya ada"],
    ["勇气", "yǒng qì", "courage", "keberanian"],
    ["不", "bù", "not", "tidak"],
    ["挪动", "nuó dòng", "move / budge", "bergerak / berganjak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["爸", "bà", "Dad", "Ayah"],
    ["气极了", "qì jí le", "furious / extremely angry", "sangat marah / naik radang"],
    ["，", "", "", ""],
    ["一下", "yí xià", "all of a sudden / at once", "dengan sekali ragut / tiba-tiba"],
    ["把", "bǎ", "particle (object marker)", ""],
    ["我", "wǒ", "me", "saya"],
    ["从", "cóng", "from", "dari"],
    ["床上", "chuáng shàng", "bed", "atas katil"],
    ["拖起来", "tuō qǐ lái", "dragged up / pulled up", "mengheret bangun / menarik keluar"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["桌上", "zhuō shàng", "table", "atas meja"],
    ["抄起", "chāo qǐ", "snatched up / grabbed", "mencapai / merenggut up"],
    ["一把", "yì bǎ", "one (measure word for duster)", "sebatang"],
    ["鸡毛掸子", "jī máo dǎn zi", "feather duster", "bulu ayam / pembersih bulu ayam"],
    ["，", "", "", ""],
    ["倒转", "dào zhuǎn", "invert / turn upside down", "menterbalikkan"],
    ["来", "lái", "to", "untuk"],
    ["拿", "ná", "hold", "memegang"],
    ["，", "", "", ""],
    ["藤鞭子", "téng biān zi", "rattan cane", "rotan / pemukul rotan"],
    ["在", "zài", "in", "di"],
    ["空中", "kōng zhōng", "air", "udara / angkasa"],
    ["一", "yī", "once / a single (swing)", "sekali"],
    ["抡", "lūn", "brandish / swing", "mengayunkan / melibas"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "terus / lalu"],
    ["发出", "fā chū", "emitted / made", "mengeluarkan / berbunyi"],
    ["咻咻的", "xiū xiū de", "swishing / whizzing", "desiran / bunyi libasan 'shiu-shiu'"],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["挨打了", "ái dǎ le", "got beaten / suffered a beating", "dipukul / kena sebat / dibelasah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["爸", "bà", "Dad", "Ayah"],
    ["把", "bǎ", "particle (object marker)", ""],
    ["我", "wǒ", "me", "saya"],
    ["从", "cóng", "from", "dari"],
    ["床下", "chuáng xià", "under the bed", "bawah katil"],
    ["打到", "dǎ dào", "beat until / to", "memukul sehinggalah ke"],
    ["床尾", "chuáng wěi", "foot of the bed", "hujung katil"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["哭号着", "kū háo zhe", "wailing / crying out loud", "menangis meraung-raung / melolong"],
    ["，", "", "", ""],
    ["躲避着", "duǒ bì zhe", "dodging / evading", "mengelak / melarikan diri"],
    ["，", "", "", ""],
    ["外面", "wài mian", "outside", "di luar"],
    ["的", "de", "particle", ""],
    ["雨声", "yǔ shēng", "sound of rain", "bunyi hujan"],
    ["混合着", "hùn hé zhe", "mixing with / blending", "bercampur dengan / bersatu dengan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["哭声", "kū shēng", "crying sound", "bunyi tangisan"],
    ["。", "", "", ""],
    ["最后", "zuì hòu", "finally", "Akhirnya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["像是一只", "xiàng shì yì zhī", "resembled a / like a", "bagaikan seekor / seperti"],
    ["狼狈", "láng bèi", "wretched / distressed / helpless", "comel-comel basah / dalam keadaan amat daif"],
    ["的", "de", "particle", "yang"],
    ["小狗", "xiǎo gǒu", "puppy", "anak anjing"],
    ["，", "", "", ""],
    ["被", "bèi", "by (passive)", "telah di-"],
    ["抱上了", "bào shàng le", "carried onto", "diangkat naik ke atas"],
    ["三轮车", "sān lún chē", "tricycle / rickshaw", "beca / kereta roda tiga"],
    ["。", "", "", ""],
    ["第一次", "dì yī cì", "for the first time", "kali pertama"],
    ["花", "huā", "spend", "membelanjakan / membayar"],
    ["五大枚", "wǔ dà méi", "five large pieces", "lima keping besar"],
    ["铜板", "tóng bǎn", "copper coins", "duit syiling tembaga"],
    ["坐车", "zuò chē", "take a vehicle / ride", "naik beca / kenderaan"],
    ["去", "qù", "go to", "pergi"],
    ["上学", "shàng xué", "school", "sekolah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["我", "wǒ", "I", "Saya"],
    ["坐在", "zuò zài", "sat inside", "duduk di dalam"],
    ["放下", "fàng xià", "put down / lowered", "menurunkan / menutup"],
    ["雨篷", "yǔ péng", "rain awning / canopy", "bumbung beca / kanopi pelindung hujan"],
    ["的", "de", "particle", "yang"],
    ["三轮车", "sān lún chē", "tricycle / rickshaw", "beca"],
    ["里", "lǐ", "inside", "dalam / di dalam"],
    ["，", "", "", ""],
    ["一边", "yì biān", "on one hand / while", "sambil / di samping"],
    ["抽抽搭搭地", "chōu chōu dā dā de", "sobbingly / whimpering", "tersedu-sedu / menangis teresak-esak dengan"],
    ["哭着", "kū zhe", "crying", "menangis"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["检查", "jiǎn chá", "inspecting / checking", "memeriksa / melihat"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["伤痕", "shāng hén", "scars / bruises / marks", "kesan luka / lebam / bilasan"],
    ["。", "", "", ""],
    ["小腿", "xiǎo tuǐ", "calf (lower leg)", "betis"],
    ["上", "shàng", "on", "atas / di atas"],
    ["那", "nà", "those", "itu"],
    ["一条条", "yì tiáo tiáo", "row after row / lines of", "berjalur-jalur / kesan panjang"],
    ["鼓起的", "gǔ qǐ de", "swollen / raised", "bengkak / timbul / melepuh"],
    ["抽痕", "chōu hén", "whip marks / welts", "kesan rotan / sebatan"],
    ["，", "", "", ""],
    ["红肿的", "hóng zhǒng de", "red and swollen", "merah dan bengkak"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "and furthermore", "malah / dan juga"],
    ["发着热", "fā zhe rè", "emitting heat / burning", "berasa panas / membahang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["拼命地", "pīn mìng de", "desperately / exerting all effort", "bermati-matian / sedaya upaya"],
    ["把", "bǎ", "particle (object marker)", ""],
    ["裙子", "qún zi", "skirt", "skirt"],
    ["向下拉了拉", "xiàng xià lā le lā", "pulled down a bit", "menarik ke bawah sedikit"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["虽然", "suī rán", "although", "Walaupun"],
    ["迟到了", "chí dào le", "was late", "lewat ke sekolah"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "namun"],
    ["老师", "lǎo shī", "teacher", "cikgu / guru"],
    ["并", "bìng", "actually", "langsung"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["罚", "fá", "punish", "mendenda"],
    ["我", "wǒ", "me", "saya"],
    ["站", "zhàn", "stand", "berdiri"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["因为", "yīn wèi", "because", "kerana / oleh sebab"],
    ["下雨天", "xià yǔ tiān", "rainy day", "hari hujan"],
    ["可以", "kě yǐ", "can be / could", "boleh"],
    ["原谅", "yuán liàng", "forgiven / excused", "dimaafkan"],
    ["的", "de", "particle", ""],
    ["缘故", "yuán gù", "reason / cause", "sebab / alasan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["老师", "lǎo shī", "teacher", "Cikgu"],
    ["教", "jiāo", "taught / instructed", "mengajar / meminta"],
    ["我们", "wǒ men", "us", "kami"],
    ["先", "xiān", "first", "terlebih dahulu"],
    ["静默", "jìng mò", "silent reflection / meditate", "berdiam diri / bertafakur / bertenang"],
    ["再", "zài", "then", "kemudian baru"],
    ["读书", "dú shū", "read aloud / study", "membaca buku"],
    ["，", "", "", ""],
    ["坐直", "zuò zhí", "sit up straight", "duduk tegak"],
    ["身子", "shēn zi", "body", "badan"],
    ["，", "", "", ""],
    ["手", "shǒu", "hands", "tangan"],
    ["背在", "bèi zài", "put behind / rest on back", "diletakkan di belakang"],
    ["身后", "shēn hòu", "behind back", "belakang badan"],
    ["，", "", "", ""],
    ["闭上", "bì shàng", "close", "menutup / memejamkan"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["，", "", "", ""],
    ["静静", "jìng jìng", "quietly", "senyap-senyap / dengan tenang"],
    ["地", "de", "particle", ""],
    ["想", "xiǎng", "reflect / think", "berfikir"],
    ["五分钟", "wǔ fēn zhōng", "five minutes", "lima minit"],
    ["。", "", "", ""],
    ["老师", "lǎo shī", "teacher", "Cikgu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["想想看", "xiǎng xiǎng kàn", "think about it / reflect", "Cuba fikirkan / renungkan"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "kamu"],
    ["是不是", "shì bú shì", "whether or not", "adakah / sama ada"],
    ["听", "tīng", "listen to / obey", "mendengar kata / patuh"],
    ["爸", "bà", "Dad", "ayah"],
    ["妈", "mā", "Mom", "ibu"],
    ["和", "hé", "and", "dan"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["的", "de", "particle", "punya"],
    ["话", "huà", "words / advice", "cakap / arahan"],
    ["？", "", "", ""],
    ["昨天", "zuó tiān", "yesterday", "semalam"],
    ["留的", "liú de", "assigned", "yang diberikan"],
    ["功课", "gōng kè", "homework", "kerja rumah"],
    ["有没有", "yǒu méi yǒu", "have you or have you not", "ada atau tidak / sudahkah"],
    ["做好", "zuò hǎo", "done well / finished", "disiapkan"],
    ["？", "", "", ""],
    ["今天", "jīn tiān", "today", "hari ini punya"],
    ["功课", "gōng kè", "homework", "kerja rumah"],
    ["全", "quán", "all", "semua sekali"],
    ["带来", "dài lái", "brought along", "bawa / dibawa bersama"],
    ["了吗", "le ma", "particle (question)", "kah / sudahkah"],
    ["？", "", "", ""],
    ["早晨", "zǎo chén", "morning", "pagi tadi"],
    ["跟", "gēn", "with / to", "dengan"],
    ["爸", "bà", "Dad", "ayah"],
    ["妈", "mā", "Mom", "ibu"],
    ["有礼貌", "yǒu lǐ mào", "politely", "dengan bersopan santun"],
    ["地", "de", "particle", ""],
    ["道别", "dào bié", "say goodbye", "mengucapkan selamat tinggal / bersalam"],
    ["了吗", "le ma", "particle", "kah"],
    ["？", "", "", ""],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["听到", "tīng dào", "heard", "mendengar"],
    ["这儿", "zhèr", "this part / here", "perkara ini / di sini"],
    ["，", "", "", ""],
    ["鼻子", "bí zi", "nose", "hidung"],
    ["不禁", "bù jīn", "cannot help but", "tidak dapat menahan / secara tidak langsung"],
    ["抽搭了", "chōu dā le", "sniffled / twitched", "tersedu / tersengkih sedikit"],
    ["一下", "yí xià", "a bit / once", "sekali"],
    ["，", "", "", ""],
    ["幸好", "xìng hǎo", "fortunately", "nasib baik / mujurlah"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["是", "shì", "were", "adalah"],
    ["闭着的", "bì zhe de", "closed", "terpejam / tertutup"],
    ["，", "", "", ""],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["不至于", "bú zhì yú", "not to the extent of", "tidak akan sampai / tidaklah"],
    ["流出来", "liú chū lái", "flow out", "mengalir keluar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段

    ["正在", "zhèng zài", "right in the middle of", "Sedang dalam keadaan / ketika"],
    ["静默", "jìng mò", "silent reflection", "bertafakur / bertenang"],
    ["当中", "dāng zhōng", "among / mid", "dalam / pertengahan"],
    ["，", "", "", ""],
    ["有人", "yǒu rén", "someone", "ada orang"],
    ["拍了", "pāi le", "patted", "menepuk"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["肩头", "jiān tóu", "shoulder", "bahu"],
    ["一下", "yí xià", "once / a bit", "sekali"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["急忙", "jí máng", "in a hurry / hastily", "dengan tergesa-gesa / segera"],
    ["睁开了", "zhēng kāi le", "opened up", "membuka wide / mencelikkan"],
    ["眼", "yǎn", "eyes", "mata"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "turn out to be", "rupa-rupanya"],
    ["是", "shì", "was", "adalah"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["站在", "zhàn zài", "standing at", "berdiri di"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["位子", "wèi zi", "seat / place", "tempat duduk"],
    ["边", "biān", "beside / side", "tepi"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["用", "yòng", "use", "menggunakan"],
    ["眼神", "yǎn shén", "expression in eyes / gaze", "isyarat mata / pandangan mata"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["让我", "ràng wǒ", "let me / ask me to", "meminta saya / biarkan saya"],
    ["向", "xiàng", "towards", "ke arah"],
    ["教室", "jiào...shì", "classroom", "kelas"],
    ["的", "de", "particle", ""],
    ["窗外", "chuāng wài", "outside window", "luar tingkap"],
    ["看去", "kàn qù", "look over", "melihat"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["猛一转头", "měng yì zhuǎn tóu", "suddenly turned head around", "memalingkan muka dengan pantas"],
    ["看", "kàn", "look / see", "dan melihat"],
    ["，", "", "", ""],
    ["是", "shì", "was / is", "adalah"],
    ["爸爸", "bà ba", "father", "ayah"],
    ["那", "nà", "that", "yang"],
    ["瘦高", "shòu gāo", "tall and thin", "tinggi lampai / kurus tinggi"],
    ["的", "de", "particle", ""],
    ["影子", "yǐng zi", "shadow / silhouette", "bayang-bayang / kelibat"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段

    ["我", "wǒ", "I", "Saya"],
    ["刚", "gāng", "just", "baru sahaja"],
    ["安静下来", "ān jìng xià lái", "calmed down", "bertenang / menjadi senyap"],
    ["的", "de", "particle", ""],
    ["心", "xīn", "heart", "hati"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi / pula"],
    ["再次", "zài cì", "once more", "sekali lagi"],
    ["波动", "bō dòng", "fluctuated / surged / moved", "berombak / bergelora / tidak tenang"],
    ["起来", "qǐ lái", "started to", "mula"],
    ["！", "", "", ""],
    ["爸爸", "bà ba", "father", "Ayah"],
    ["为什么", "wèi shén me", "why", "kenapakah / mengapa"],
    ["追到", "zhuī dào", "chased up to / came all the way", "mengejar sehingga ke"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["来", "lái", "come", "datang"],
    ["？", "", "", ""],
    ["爸爸", "bà ba", "father", "Ayah"],
    ["点头", "diǎn tóu", "nodded head", "mengangguk kepala"],
    ["招", "zhāo", "beckoned / waved", "memanggil / memberi isyarat"],
    ["我", "wǒ", "me", "saya"],
    ["出去", "chū qù", "go out", "keluar"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["看看", "kàn kàn", "looked at", "melihat"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["，", "", "", ""],
    ["征求", "zhēng qiú", "seek / ask for", "meminta / memohon"],
    ["他的", "tā de", "his", "dia punya"],
    ["同意", "tóng yì", "permission / agreement", "keizinan / persetujuan"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["微笑地", "wēi xiào de", "smilingly", "dengan tersenyum"],
    ["点点头", "diǎn diǎn tóu", "nodded head", "mengangguk kepala"],
    ["，", "", "", ""],
    ["表示", "biǎo shì", "expressing / indicating", "menandakan / menunjukkan"],
    ["答应", "dā ying", "permit / agree", "membenarkan / mengizinkan"],
    ["我", "wǒ", "me", "saya"],
    ["出去", "chū qù", "go out", "keluar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 16 段

    ["我", "wǒ", "I", "Saya"],
    ["走出了", "zǒu chū le", "walked out of", "melangkah keluar dari"],
    ["教室", "jiào shì", "classroom", "kelas"],
    ["，", "", "", ""],
    ["站在", "zhàn zài", "standing before", "berdiri di hadapan"],
    ["爸", "bà", "Dad", "ayah"],
    ["面前", "miàn qián", "in front of", "muka / depan"],
    ["。", "", "", ""],
    ["爸", "bà", "Dad", "Ayah"],
    ["什么", "shén me", "anything", "apa-apa pun"],
    ["也", "yě", "also (not)", "langsung tidak"],
    ["没说", "méi shuō", "didn't say", "berkata"],
    ["，", "", "", ""],
    ["打开了", "dǎ kāi le", "opened up", "membuka"],
    ["手中", "shǒu zhōng", "in the hand", "dalam genggaman tangan / bungkusan"],
    ["的", "de", "particle", "yang ada di"],
    ["包袱", "bāo fu", "cloth bundle / package", "bungkusan kain"],
    ["，", "", "", ""],
    ["拿出来", "ná chū lái", "took out", "mengeluarkan"],
    ["的", "de", "particle", ""],
    ["是", "shì", "was", "adalah"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["花夹袄", "huā jiá ǎo", "patterned lined jacket", "baju sejuk berbunga / jaket bertali"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["递给我", "dì gěi wǒ", "handed to me", "menyerahkan kepada saya"],
    ["，", "", "", ""],
    ["看着", "kàn zhe", "watching", "melihat / memperhatikan"],
    ["我", "wǒ", "me", "saya"],
    ["穿上", "chuān shàng", "put on (clothes)", "memakainya"],
    ["，", "", "", ""],
    ["又", "yòu", "and also / again", "dan juga / kemudian"],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["两个", "liǎng gè", "two pieces of", "dua keping"],
    ["铜板", "tóng bǎn", "copper coins", "duit syiling tembaga"],
    ["给我", "gěi wǒ", "give me", "kepada saya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 17 段

    ["后来", "hòu lái", "afterwards / later on", "Kemudian / selepas itu"],
    ["怎么样", "zěn me yàng", "how it went / what happened", "bagaimana kesudahannya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["已经", "yǐ jīng", "already", "sudah / telah"],
    ["记不得", "jì bù dé", "cannot remember", "tidak dapat ingat / lupa"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["只", "zhǐ", "only", "Hanya"],
    ["记得", "jì dé", "remember", "ingat"],
    ["从那以后", "cóng nà yǐ hòu", "from then onwards", "sejak dari hari itu / semenjak itu"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["早晨", "zǎo chén", "morning", "pagi / awal pagi"],
    ["我", "wǒ", "I", "saya"],
    ["都是", "dōu shì", "always was / am", "adalah sentiasa menjadi"],
    ["站在", "zhàn zài", "standing at", "berdiri di"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["门口", "mén kǒu", "gate / entrance", "pintu pagar / pintu masuk"],
    ["，", "", "", ""],
    ["等待着", "děng dài zhe", "waiting for", "menunggu"],
    ["校工", "xiào gōng", "school janitor / worker", "pekerja sekolah / tukang kebun sekolah"],
    ["开", "kāi", "open", "membuka"],
    ["大铁栅", "dà tiě zhà", "large iron gate", "pintu pagar besi yang besar"],
    ["的", "de", "particle", "yang"],
    ["一个", "yí gè", "a / one", "seorang"],
    ["学生", "xué sheng", "student", "pelajar / murid"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 文末出处

    // 文末作者出处
    ["（", "", "", ""],
    ["林海音", "lín hǎi yīn", "Lin Haiyin (Author)", "Lin Haiyin (Penulis)"],
    ["《", "", "", ""],
    ["迟到", "chí dào", "Late", "Lewat"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with / has", "ada"],
    ["改动", "gǎi dòng", "adaptations / modifications", "perubahan / ubah suai"],
    ["）", "", "", ""]
];
